"""add equipment rental foundation

Revision ID: 104ae669cc1a
Revises: b27e8d5f64c1
Create Date: 2026-07-18 21:44:39.423944

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "104ae669cc1a"
down_revision: str | Sequence[str] | None = "b27e8d5f64c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rental_categories",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["rental_categories.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_rental_categories_active_sort",
        "rental_categories",
        ["is_active", "sort_order"],
        unique=False,
    )
    op.create_index(op.f("ix_rental_categories_code"), "rental_categories", ["code"], unique=True)
    op.create_index(
        op.f("ix_rental_categories_is_active"), "rental_categories", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_rental_categories_parent_id"), "rental_categories", ["parent_id"], unique=False
    )
    op.create_index(
        op.f("ix_rental_categories_title"), "rental_categories", ["title"], unique=False
    )
    op.create_table(
        "rental_lessor_profiles",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("display_name", sa.String(length=150), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("province_id", sa.BigInteger(), nullable=True),
        sa.Column("city_id", sa.BigInteger(), nullable=True),
        sa.Column("address_text", sa.Text(), nullable=True),
        sa.Column("avatar_media_file_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("admin_note", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("approved_by", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["approved_by"], ["auth_users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["avatar_media_file_id"], ["media_files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["auth_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_rental_lessor_geo", "rental_lessor_profiles", ["province_id", "city_id"], unique=False
    )
    op.create_index(
        op.f("ix_rental_lessor_profiles_approved_by"),
        "rental_lessor_profiles",
        ["approved_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rental_lessor_profiles_avatar_media_file_id"),
        "rental_lessor_profiles",
        ["avatar_media_file_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rental_lessor_profiles_city_id"),
        "rental_lessor_profiles",
        ["city_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rental_lessor_profiles_province_id"),
        "rental_lessor_profiles",
        ["province_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rental_lessor_profiles_status"), "rental_lessor_profiles", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_rental_lessor_profiles_user_id"),
        "rental_lessor_profiles",
        ["user_id"],
        unique=True,
    )
    op.create_index(
        "ix_rental_lessor_status_deleted",
        "rental_lessor_profiles",
        ["status", "deleted_at"],
        unique=False,
    )
    op.create_table(
        "rental_equipment",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("lessor_profile_id", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=220), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("manufacturer", sa.String(length=120), nullable=True),
        sa.Column("model_name", sa.String(length=120), nullable=True),
        sa.Column("production_year", sa.Integer(), nullable=True),
        sa.Column("operator_mode", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("province_id", sa.BigInteger(), nullable=True),
        sa.Column("city_id", sa.BigInteger(), nullable=True),
        sa.Column("address_text", sa.Text(), nullable=True),
        sa.Column("delivery_available", sa.Boolean(), nullable=False),
        sa.Column("delivery_terms", sa.Text(), nullable=True),
        sa.Column("security_deposit_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("admin_note", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("approved_by", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "security_deposit_amount IS NULL OR security_deposit_amount >= 0",
            name="ck_rental_equipment_deposit_nonnegative",
        ),
        sa.ForeignKeyConstraint(["approved_by"], ["auth_users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["category_id"], ["rental_categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["lessor_profile_id"], ["rental_lessor_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lessor_profile_id", "slug", name="uq_rental_equipment_lessor_slug"),
    )
    op.create_index(
        op.f("ix_rental_equipment_approved_by"), "rental_equipment", ["approved_by"], unique=False
    )
    op.create_index(
        op.f("ix_rental_equipment_category_id"), "rental_equipment", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_rental_equipment_city_id"), "rental_equipment", ["city_id"], unique=False
    )
    op.create_index(
        "ix_rental_equipment_geo", "rental_equipment", ["province_id", "city_id"], unique=False
    )
    op.create_index(
        op.f("ix_rental_equipment_is_active"), "rental_equipment", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_rental_equipment_lessor_profile_id"),
        "rental_equipment",
        ["lessor_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rental_equipment_operator_mode"),
        "rental_equipment",
        ["operator_mode"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rental_equipment_province_id"), "rental_equipment", ["province_id"], unique=False
    )
    op.create_index(
        "ix_rental_equipment_public",
        "rental_equipment",
        ["status", "is_active", "deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rental_equipment_status"), "rental_equipment", ["status"], unique=False
    )
    op.create_index(op.f("ix_rental_equipment_title"), "rental_equipment", ["title"], unique=False)
    op.create_table(
        "rental_availability_blocks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("equipment_id", sa.BigInteger(), nullable=False),
        sa.Column("block_type", sa.String(length=30), nullable=False),
        sa.Column("starts_at", sa.DateTime(), nullable=False),
        sa.Column("ends_at", sa.DateTime(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("ends_at > starts_at", name="ck_rental_availability_valid_range"),
        sa.ForeignKeyConstraint(["created_by"], ["auth_users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["equipment_id"], ["rental_equipment.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rental_availability_blocks_block_type"),
        "rental_availability_blocks",
        ["block_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rental_availability_blocks_created_by"),
        "rental_availability_blocks",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rental_availability_blocks_ends_at"),
        "rental_availability_blocks",
        ["ends_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rental_availability_blocks_equipment_id"),
        "rental_availability_blocks",
        ["equipment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rental_availability_blocks_starts_at"),
        "rental_availability_blocks",
        ["starts_at"],
        unique=False,
    )
    op.create_index(
        "ix_rental_availability_equipment_range",
        "rental_availability_blocks",
        ["equipment_id", "starts_at", "ends_at"],
        unique=False,
    )
    op.create_table(
        "rental_equipment_media",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("equipment_id", sa.BigInteger(), nullable=False),
        sa.Column("media_file_id", sa.BigInteger(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("alt_text", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["equipment_id"], ["rental_equipment.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["media_file_id"], ["media_files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("equipment_id", "media_file_id", name="uq_rental_equipment_media_file"),
    )
    op.create_index(
        op.f("ix_rental_equipment_media_equipment_id"),
        "rental_equipment_media",
        ["equipment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rental_equipment_media_is_primary"),
        "rental_equipment_media",
        ["is_primary"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rental_equipment_media_media_file_id"),
        "rental_equipment_media",
        ["media_file_id"],
        unique=False,
    )
    op.create_index(
        "ix_rental_equipment_media_sort",
        "rental_equipment_media",
        ["equipment_id", "sort_order"],
        unique=False,
    )
    op.create_table(
        "rental_pricing_rules",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("equipment_id", sa.BigInteger(), nullable=False),
        sa.Column("unit", sa.String(length=30), nullable=False),
        sa.Column("operator_included", sa.Boolean(), nullable=False),
        sa.Column("price_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("minimum_units", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("minimum_units > 0", name="ck_rental_pricing_minimum_positive"),
        sa.CheckConstraint("price_amount > 0", name="ck_rental_pricing_price_positive"),
        sa.ForeignKeyConstraint(["equipment_id"], ["rental_equipment.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "equipment_id",
            "unit",
            "operator_included",
            name="uq_rental_pricing_equipment_unit_operator",
        ),
    )
    op.create_index(
        op.f("ix_rental_pricing_rules_equipment_id"),
        "rental_pricing_rules",
        ["equipment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rental_pricing_rules_is_active"),
        "rental_pricing_rules",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rental_pricing_rules_unit"), "rental_pricing_rules", ["unit"], unique=False
    )
    op.create_table(
        "rental_requests",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("requester_user_id", sa.BigInteger(), nullable=False),
        sa.Column("lessor_profile_id", sa.BigInteger(), nullable=False),
        sa.Column("equipment_id", sa.BigInteger(), nullable=False),
        sa.Column("pricing_rule_id", sa.BigInteger(), nullable=False),
        sa.Column("starts_at", sa.DateTime(), nullable=False),
        sa.Column("ends_at", sa.DateTime(), nullable=False),
        sa.Column("requested_units", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("operator_requested", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("price_per_unit_snapshot", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("rental_amount_snapshot", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("deposit_amount_snapshot", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("total_amount_snapshot", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("delivery_address", sa.Text(), nullable=True),
        sa.Column("requester_note", sa.Text(), nullable=True),
        sa.Column("lessor_note", sa.Text(), nullable=True),
        sa.Column("admin_note", sa.Text(), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("ends_at > starts_at", name="ck_rental_request_valid_range"),
        sa.CheckConstraint(
            "price_per_unit_snapshot IS NULL OR price_per_unit_snapshot >= 0",
            name="ck_rental_request_unit_price_nonnegative",
        ),
        sa.CheckConstraint("requested_units > 0", name="ck_rental_request_units_positive"),
        sa.CheckConstraint(
            "total_amount_snapshot IS NULL OR total_amount_snapshot >= 0",
            name="ck_rental_request_total_nonnegative",
        ),
        sa.ForeignKeyConstraint(["equipment_id"], ["rental_equipment.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["lessor_profile_id"], ["rental_lessor_profiles.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["pricing_rule_id"], ["rental_pricing_rules.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["requester_user_id"], ["auth_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rental_requests_ends_at"), "rental_requests", ["ends_at"], unique=False
    )
    op.create_index(
        op.f("ix_rental_requests_equipment_id"), "rental_requests", ["equipment_id"], unique=False
    )
    op.create_index(
        "ix_rental_requests_equipment_range_status",
        "rental_requests",
        ["equipment_id", "starts_at", "ends_at", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rental_requests_lessor_profile_id"),
        "rental_requests",
        ["lessor_profile_id"],
        unique=False,
    )
    op.create_index(
        "ix_rental_requests_lessor_status",
        "rental_requests",
        ["lessor_profile_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rental_requests_pricing_rule_id"),
        "rental_requests",
        ["pricing_rule_id"],
        unique=False,
    )
    op.create_index(
        "ix_rental_requests_requester_status",
        "rental_requests",
        ["requester_user_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rental_requests_requester_user_id"),
        "rental_requests",
        ["requester_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rental_requests_starts_at"), "rental_requests", ["starts_at"], unique=False
    )
    op.create_index(op.f("ix_rental_requests_status"), "rental_requests", ["status"], unique=False)
    op.create_table(
        "rental_request_status_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.BigInteger(), nullable=False),
        sa.Column("changed_by", sa.BigInteger(), nullable=True),
        sa.Column("from_status", sa.String(length=30), nullable=True),
        sa.Column("to_status", sa.String(length=30), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("event_key", sa.String(length=160), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["changed_by"], ["auth_users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["request_id"], ["rental_requests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_rental_request_logs_request_created",
        "rental_request_status_logs",
        ["request_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rental_request_status_logs_changed_by"),
        "rental_request_status_logs",
        ["changed_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rental_request_status_logs_event_key"),
        "rental_request_status_logs",
        ["event_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_rental_request_status_logs_request_id"),
        "rental_request_status_logs",
        ["request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rental_request_status_logs_to_status"),
        "rental_request_status_logs",
        ["to_status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_rental_request_status_logs_to_status"), table_name="rental_request_status_logs"
    )
    op.drop_index(
        op.f("ix_rental_request_status_logs_request_id"), table_name="rental_request_status_logs"
    )
    op.drop_index(
        op.f("ix_rental_request_status_logs_event_key"), table_name="rental_request_status_logs"
    )
    op.drop_index(
        op.f("ix_rental_request_status_logs_changed_by"), table_name="rental_request_status_logs"
    )
    op.drop_index("ix_rental_request_logs_request_created", table_name="rental_request_status_logs")
    op.drop_table("rental_request_status_logs")
    op.drop_index(op.f("ix_rental_requests_status"), table_name="rental_requests")
    op.drop_index(op.f("ix_rental_requests_starts_at"), table_name="rental_requests")
    op.drop_index(op.f("ix_rental_requests_requester_user_id"), table_name="rental_requests")
    op.drop_index("ix_rental_requests_requester_status", table_name="rental_requests")
    op.drop_index(op.f("ix_rental_requests_pricing_rule_id"), table_name="rental_requests")
    op.drop_index("ix_rental_requests_lessor_status", table_name="rental_requests")
    op.drop_index(op.f("ix_rental_requests_lessor_profile_id"), table_name="rental_requests")
    op.drop_index("ix_rental_requests_equipment_range_status", table_name="rental_requests")
    op.drop_index(op.f("ix_rental_requests_equipment_id"), table_name="rental_requests")
    op.drop_index(op.f("ix_rental_requests_ends_at"), table_name="rental_requests")
    op.drop_table("rental_requests")
    op.drop_index(op.f("ix_rental_pricing_rules_unit"), table_name="rental_pricing_rules")
    op.drop_index(op.f("ix_rental_pricing_rules_is_active"), table_name="rental_pricing_rules")
    op.drop_index(op.f("ix_rental_pricing_rules_equipment_id"), table_name="rental_pricing_rules")
    op.drop_table("rental_pricing_rules")
    op.drop_index("ix_rental_equipment_media_sort", table_name="rental_equipment_media")
    op.drop_index(
        op.f("ix_rental_equipment_media_media_file_id"), table_name="rental_equipment_media"
    )
    op.drop_index(op.f("ix_rental_equipment_media_is_primary"), table_name="rental_equipment_media")
    op.drop_index(
        op.f("ix_rental_equipment_media_equipment_id"), table_name="rental_equipment_media"
    )
    op.drop_table("rental_equipment_media")
    op.drop_index("ix_rental_availability_equipment_range", table_name="rental_availability_blocks")
    op.drop_index(
        op.f("ix_rental_availability_blocks_starts_at"), table_name="rental_availability_blocks"
    )
    op.drop_index(
        op.f("ix_rental_availability_blocks_equipment_id"), table_name="rental_availability_blocks"
    )
    op.drop_index(
        op.f("ix_rental_availability_blocks_ends_at"), table_name="rental_availability_blocks"
    )
    op.drop_index(
        op.f("ix_rental_availability_blocks_created_by"), table_name="rental_availability_blocks"
    )
    op.drop_index(
        op.f("ix_rental_availability_blocks_block_type"), table_name="rental_availability_blocks"
    )
    op.drop_table("rental_availability_blocks")
    op.drop_index(op.f("ix_rental_equipment_title"), table_name="rental_equipment")
    op.drop_index(op.f("ix_rental_equipment_status"), table_name="rental_equipment")
    op.drop_index("ix_rental_equipment_public", table_name="rental_equipment")
    op.drop_index(op.f("ix_rental_equipment_province_id"), table_name="rental_equipment")
    op.drop_index(op.f("ix_rental_equipment_operator_mode"), table_name="rental_equipment")
    op.drop_index(op.f("ix_rental_equipment_lessor_profile_id"), table_name="rental_equipment")
    op.drop_index(op.f("ix_rental_equipment_is_active"), table_name="rental_equipment")
    op.drop_index("ix_rental_equipment_geo", table_name="rental_equipment")
    op.drop_index(op.f("ix_rental_equipment_city_id"), table_name="rental_equipment")
    op.drop_index(op.f("ix_rental_equipment_category_id"), table_name="rental_equipment")
    op.drop_index(op.f("ix_rental_equipment_approved_by"), table_name="rental_equipment")
    op.drop_table("rental_equipment")
    op.drop_index("ix_rental_lessor_status_deleted", table_name="rental_lessor_profiles")
    op.drop_index(op.f("ix_rental_lessor_profiles_user_id"), table_name="rental_lessor_profiles")
    op.drop_index(op.f("ix_rental_lessor_profiles_status"), table_name="rental_lessor_profiles")
    op.drop_index(
        op.f("ix_rental_lessor_profiles_province_id"), table_name="rental_lessor_profiles"
    )
    op.drop_index(op.f("ix_rental_lessor_profiles_city_id"), table_name="rental_lessor_profiles")
    op.drop_index(
        op.f("ix_rental_lessor_profiles_avatar_media_file_id"), table_name="rental_lessor_profiles"
    )
    op.drop_index(
        op.f("ix_rental_lessor_profiles_approved_by"), table_name="rental_lessor_profiles"
    )
    op.drop_index("ix_rental_lessor_geo", table_name="rental_lessor_profiles")
    op.drop_table("rental_lessor_profiles")
    op.drop_index(op.f("ix_rental_categories_title"), table_name="rental_categories")
    op.drop_index(op.f("ix_rental_categories_parent_id"), table_name="rental_categories")
    op.drop_index(op.f("ix_rental_categories_is_active"), table_name="rental_categories")
    op.drop_index(op.f("ix_rental_categories_code"), table_name="rental_categories")
    op.drop_index("ix_rental_categories_active_sort", table_name="rental_categories")
    op.drop_table("rental_categories")
    # ### end Alembic commands ###
