"""add media file table

Revision ID: 3744815d3d2e
Revises: 05d440a0388b
Create Date: 2026-05-20 18:26:29.335173

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3744815d3d2e'
down_revision: str | Sequence[str] | None = '05d440a0388b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=True),
    sa.Column('file_key', sa.String(length=80), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('relative_path', sa.String(length=500), nullable=False),
    sa.Column('storage_disk', sa.String(length=50), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('visibility', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('purpose', sa.String(length=80), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_disk', 'relative_path', name='uq_media_files_disk_relative_path')
    )
    op.create_index(op.f('ix_media_files_checksum_sha256'), 'media_files', ['checksum_sha256'], unique=False)
    op.create_index('ix_media_files_created', 'media_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_media_files_extension'), 'media_files', ['extension'], unique=False)
    op.create_index(op.f('ix_media_files_file_key'), 'media_files', ['file_key'], unique=True)
    op.create_index(op.f('ix_media_files_mime_type'), 'media_files', ['mime_type'], unique=False)
    op.create_index('ix_media_files_owner_status', 'media_files', ['owner_user_id', 'status'], unique=False)
    op.create_index(op.f('ix_media_files_owner_user_id'), 'media_files', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_media_files_purpose'), 'media_files', ['purpose'], unique=False)
    op.create_index('ix_media_files_purpose_visibility_status', 'media_files', ['purpose', 'visibility', 'status'], unique=False)
    op.create_index(op.f('ix_media_files_status'), 'media_files', ['status'], unique=False)
    op.create_index(op.f('ix_media_files_storage_disk'), 'media_files', ['storage_disk'], unique=False)
    op.create_index(op.f('ix_media_files_visibility'), 'media_files', ['visibility'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_files_visibility'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_storage_disk'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_status'), table_name='media_files')
    op.drop_index('ix_media_files_purpose_visibility_status', table_name='media_files')
    op.drop_index(op.f('ix_media_files_purpose'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_owner_user_id'), table_name='media_files')
    op.drop_index('ix_media_files_owner_status', table_name='media_files')
    op.drop_index(op.f('ix_media_files_mime_type'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_file_key'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_extension'), table_name='media_files')
    op.drop_index('ix_media_files_created', table_name='media_files')
    op.drop_index(op.f('ix_media_files_checksum_sha256'), table_name='media_files')
    op.drop_table('media_files')
    # ### end Alembic commands ###
