"""add weather tables

Revision ID: 42b49a30fc87
Revises: 62317644a66c
Create Date: 2026-05-25 13:10:46.018769

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '42b49a30fc87'
down_revision: str | Sequence[str] | None = '62317644a66c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_alert_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('title_template', sa.String(length=255), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('rule_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weather_alert_rules_type_active', 'weather_alert_rules', ['alert_type', 'is_active'], unique=False)
    op.create_table('weather_locations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('province_id', sa.BigInteger(), nullable=True),
    sa.Column('city_id', sa.BigInteger(), nullable=True),
    sa.Column('village_id', sa.BigInteger(), nullable=True),
    sa.Column('province_name', sa.String(length=120), nullable=True),
    sa.Column('city_name', sa.String(length=120), nullable=True),
    sa.Column('village_name', sa.String(length=120), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('location_type', sa.String(length=30), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_locations_city_id'), 'weather_locations', ['city_id'], unique=False)
    op.create_index(op.f('ix_weather_locations_country_code'), 'weather_locations', ['country_code'], unique=False)
    op.create_index('ix_weather_locations_geo_ids', 'weather_locations', ['province_id', 'city_id', 'village_id'], unique=False)
    op.create_index('ix_weather_locations_lat_lon', 'weather_locations', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_weather_locations_province_id'), 'weather_locations', ['province_id'], unique=False)
    op.create_index(op.f('ix_weather_locations_village_id'), 'weather_locations', ['village_id'], unique=False)
    op.create_table('weather_provider_configs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('api_key_ref', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.BigInteger(), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', name='uq_weather_provider_configs_provider')
    )
    op.create_index('ix_weather_provider_configs_active_priority', 'weather_provider_configs', ['is_active', 'priority'], unique=False)
    op.create_table('weather_alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=True),
    sa.Column('alert_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['weather_locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['weather_alert_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weather_alerts_location_active', 'weather_alerts', ['location_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_weather_alerts_location_id'), 'weather_alerts', ['location_id'], unique=False)
    op.create_index(op.f('ix_weather_alerts_rule_id'), 'weather_alerts', ['rule_id'], unique=False)
    op.create_index('ix_weather_alerts_starts_ends', 'weather_alerts', ['starts_at', 'ends_at'], unique=False)
    op.create_index('ix_weather_alerts_type_status', 'weather_alerts', ['alert_type', 'status'], unique=False)
    op.create_table('weather_forecasts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('forecast_type', sa.String(length=30), nullable=False),
    sa.Column('forecast_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('min_temperature_c', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('max_temperature_c', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('humidity_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('precipitation_mm', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('precipitation_probability', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_speed_mps', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('condition_code', sa.String(length=80), nullable=True),
    sa.Column('condition_text', sa.String(length=255), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['weather_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'provider', 'forecast_type', 'forecast_time', name='uq_weather_forecasts_location_provider_type_time')
    )
    op.create_index(op.f('ix_weather_forecasts_location_id'), 'weather_forecasts', ['location_id'], unique=False)
    op.create_index('ix_weather_forecasts_location_time', 'weather_forecasts', ['location_id', 'forecast_time'], unique=False)
    op.create_index('ix_weather_forecasts_provider_time', 'weather_forecasts', ['provider', 'forecast_time'], unique=False)
    op.create_table('weather_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('feels_like_c', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('humidity_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_speed_mps', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('wind_direction_deg', sa.BigInteger(), nullable=True),
    sa.Column('pressure_hpa', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('condition_code', sa.String(length=80), nullable=True),
    sa.Column('condition_text', sa.String(length=255), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['weather_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_snapshots_location_id'), 'weather_snapshots', ['location_id'], unique=False)
    op.create_index('ix_weather_snapshots_location_observed', 'weather_snapshots', ['location_id', 'observed_at'], unique=False)
    op.create_index('ix_weather_snapshots_provider_observed', 'weather_snapshots', ['provider', 'observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weather_snapshots_provider_observed', table_name='weather_snapshots')
    op.drop_index('ix_weather_snapshots_location_observed', table_name='weather_snapshots')
    op.drop_index(op.f('ix_weather_snapshots_location_id'), table_name='weather_snapshots')
    op.drop_table('weather_snapshots')
    op.drop_index('ix_weather_forecasts_provider_time', table_name='weather_forecasts')
    op.drop_index('ix_weather_forecasts_location_time', table_name='weather_forecasts')
    op.drop_index(op.f('ix_weather_forecasts_location_id'), table_name='weather_forecasts')
    op.drop_table('weather_forecasts')
    op.drop_index('ix_weather_alerts_type_status', table_name='weather_alerts')
    op.drop_index('ix_weather_alerts_starts_ends', table_name='weather_alerts')
    op.drop_index(op.f('ix_weather_alerts_rule_id'), table_name='weather_alerts')
    op.drop_index(op.f('ix_weather_alerts_location_id'), table_name='weather_alerts')
    op.drop_index('ix_weather_alerts_location_active', table_name='weather_alerts')
    op.drop_table('weather_alerts')
    op.drop_index('ix_weather_provider_configs_active_priority', table_name='weather_provider_configs')
    op.drop_table('weather_provider_configs')
    op.drop_index(op.f('ix_weather_locations_village_id'), table_name='weather_locations')
    op.drop_index(op.f('ix_weather_locations_province_id'), table_name='weather_locations')
    op.drop_index('ix_weather_locations_lat_lon', table_name='weather_locations')
    op.drop_index('ix_weather_locations_geo_ids', table_name='weather_locations')
    op.drop_index(op.f('ix_weather_locations_country_code'), table_name='weather_locations')
    op.drop_index(op.f('ix_weather_locations_city_id'), table_name='weather_locations')
    op.drop_table('weather_locations')
    op.drop_index('ix_weather_alert_rules_type_active', table_name='weather_alert_rules')
    op.drop_table('weather_alert_rules')
    # ### end Alembic commands ###
