"""add expert answer tables

Revision ID: 59bb20547fd2
Revises: e35a7d8c4545
Create Date: 2026-06-11 13:58:25.054663

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '59bb20547fd2'
down_revision: str | Sequence[str] | None = 'e35a7d8c4545'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expert_answers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('expert_user_id', sa.BigInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='published', nullable=False),
    sa.Column('is_accepted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('helpful_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('reports_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['expert_user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_answers_accepted_by_user_id'), 'expert_answers', ['accepted_by_user_id'], unique=False)
    op.create_index('ix_expert_answers_expert_status_created', 'expert_answers', ['expert_user_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_expert_answers_expert_user_id'), 'expert_answers', ['expert_user_id'], unique=False)
    op.create_index(op.f('ix_expert_answers_is_accepted'), 'expert_answers', ['is_accepted'], unique=False)
    op.create_index(op.f('ix_expert_answers_post_id'), 'expert_answers', ['post_id'], unique=False)
    op.create_index('ix_expert_answers_post_status_created', 'expert_answers', ['post_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_expert_answers_status'), 'expert_answers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expert_answers_status'), table_name='expert_answers')
    op.drop_index('ix_expert_answers_post_status_created', table_name='expert_answers')
    op.drop_index(op.f('ix_expert_answers_post_id'), table_name='expert_answers')
    op.drop_index(op.f('ix_expert_answers_is_accepted'), table_name='expert_answers')
    op.drop_index(op.f('ix_expert_answers_expert_user_id'), table_name='expert_answers')
    op.drop_index('ix_expert_answers_expert_status_created', table_name='expert_answers')
    op.drop_index(op.f('ix_expert_answers_accepted_by_user_id'), table_name='expert_answers')
    op.drop_table('expert_answers')
    # ### end Alembic commands ###
