"""add notification tables

Revision ID: 62317644a66c
Revises: bdc99919ffc6
Create Date: 2026-05-22 12:30:41.218014

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '62317644a66c'
down_revision: str | Sequence[str] | None = 'bdc99919ffc6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_key', sa.String(length=80), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('source_type', sa.String(length=80), nullable=True),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    op.create_index(op.f('ix_notification_events_actor_user_id'), 'notification_events', ['actor_user_id'], unique=False)
    op.create_index('ix_notification_events_source', 'notification_events', ['source_type', 'source_id'], unique=False)
    op.create_index('ix_notification_events_type_created', 'notification_events', ['event_type', 'created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('recipient_user_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['notification_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_event_id'), 'notifications', ['event_id'], unique=False)
    op.create_index('ix_notifications_recipient_channel_created', 'notifications', ['recipient_user_id', 'channel', 'created_at'], unique=False)
    op.create_index('ix_notifications_recipient_status_created', 'notifications', ['recipient_user_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.create_index('ix_notifications_status_created', 'notifications', ['status', 'created_at'], unique=False)
    op.create_table('notification_delivery_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('notification_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('provider_message_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_message_id', name='uq_notification_delivery_provider_message')
    )
    op.create_index('ix_notification_delivery_logs_notification_channel', 'notification_delivery_logs', ['notification_id', 'channel'], unique=False)
    op.create_index(op.f('ix_notification_delivery_logs_notification_id'), 'notification_delivery_logs', ['notification_id'], unique=False)
    op.create_index('ix_notification_delivery_logs_status_created', 'notification_delivery_logs', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_delivery_logs_status_created', table_name='notification_delivery_logs')
    op.drop_index(op.f('ix_notification_delivery_logs_notification_id'), table_name='notification_delivery_logs')
    op.drop_index('ix_notification_delivery_logs_notification_channel', table_name='notification_delivery_logs')
    op.drop_table('notification_delivery_logs')
    op.drop_index('ix_notifications_status_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_recipient_status_created', table_name='notifications')
    op.drop_index('ix_notifications_recipient_channel_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_event_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_notification_events_type_created', table_name='notification_events')
    op.drop_index('ix_notification_events_source', table_name='notification_events')
    op.drop_index(op.f('ix_notification_events_actor_user_id'), table_name='notification_events')
    op.drop_table('notification_events')
    # ### end Alembic commands ###
