"""add document soft delete

Revision ID: 7494f17b14e8
Revises: ed39d44aae11
Create Date: 2026-05-11 15:59:47.764806

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7494f17b14e8'
down_revision: str | Sequence[str] | None = 'ed39d44aae11'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_documents', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_documents', 'deleted_at')
    # ### end Alembic commands ###
