"""add product catalog tables

Revision ID: 830a1cd730bb
Revises: ec5e6bb244c3
Create Date: 2026-05-17 19:45:12.925315

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '830a1cd730bb'
down_revision: str | Sequence[str] | None = 'ec5e6bb244c3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['product_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_is_active'), 'product_categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=False)
    op.create_index('ix_product_categories_parent_active', 'product_categories', ['parent_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_product_categories_parent_id'), 'product_categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_product_categories_slug'), 'product_categories', ['slug'], unique=True)
    op.create_index('ix_product_categories_sort', 'product_categories', ['sort_order', 'name'], unique=False)
    op.create_table('store_products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=220), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('compare_at_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('min_order_quantity', sa.Integer(), nullable=False),
    sa.Column('max_order_quantity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('suspended_at', sa.DateTime(), nullable=True),
    sa.Column('suspended_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suspended_by'], ['auth_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'sku', name='uq_store_products_store_sku'),
    sa.UniqueConstraint('store_id', 'slug', name='uq_store_products_store_slug')
    )
    op.create_index(op.f('ix_store_products_category_id'), 'store_products', ['category_id'], unique=False)
    op.create_index('ix_store_products_category_status', 'store_products', ['category_id', 'status'], unique=False)
    op.create_index(op.f('ix_store_products_is_active'), 'store_products', ['is_active'], unique=False)
    op.create_index(op.f('ix_store_products_is_featured'), 'store_products', ['is_featured'], unique=False)
    op.create_index(op.f('ix_store_products_name'), 'store_products', ['name'], unique=False)
    op.create_index('ix_store_products_price', 'store_products', ['price'], unique=False)
    op.create_index('ix_store_products_public_lookup', 'store_products', ['status', 'deleted_at', 'is_active'], unique=False)
    op.create_index(op.f('ix_store_products_sku'), 'store_products', ['sku'], unique=False)
    op.create_index(op.f('ix_store_products_slug'), 'store_products', ['slug'], unique=False)
    op.create_index(op.f('ix_store_products_status'), 'store_products', ['status'], unique=False)
    op.create_index(op.f('ix_store_products_store_id'), 'store_products', ['store_id'], unique=False)
    op.create_index('ix_store_products_store_status', 'store_products', ['store_id', 'status'], unique=False)
    op.create_index(op.f('ix_store_products_suspended_by'), 'store_products', ['suspended_by'], unique=False)
    op.create_index(op.f('ix_store_products_unit'), 'store_products', ['unit'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['store_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_is_primary'), 'product_images', ['is_primary'], unique=False)
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_index('ix_product_images_product_primary', 'product_images', ['product_id', 'is_primary'], unique=False)
    op.create_index('ix_product_images_product_sort', 'product_images', ['product_id', 'sort_order'], unique=False)
    op.create_table('product_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=True),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['auth_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['store_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_status_history_changed_by'), 'product_status_history', ['changed_by'], unique=False)
    op.create_index('ix_product_status_history_product_created', 'product_status_history', ['product_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_product_status_history_product_id'), 'product_status_history', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_status_history_to_status'), 'product_status_history', ['to_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_status_history_to_status'), table_name='product_status_history')
    op.drop_index(op.f('ix_product_status_history_product_id'), table_name='product_status_history')
    op.drop_index('ix_product_status_history_product_created', table_name='product_status_history')
    op.drop_index(op.f('ix_product_status_history_changed_by'), table_name='product_status_history')
    op.drop_table('product_status_history')
    op.drop_index('ix_product_images_product_sort', table_name='product_images')
    op.drop_index('ix_product_images_product_primary', table_name='product_images')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_index(op.f('ix_product_images_is_primary'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_store_products_unit'), table_name='store_products')
    op.drop_index(op.f('ix_store_products_suspended_by'), table_name='store_products')
    op.drop_index('ix_store_products_store_status', table_name='store_products')
    op.drop_index(op.f('ix_store_products_store_id'), table_name='store_products')
    op.drop_index(op.f('ix_store_products_status'), table_name='store_products')
    op.drop_index(op.f('ix_store_products_slug'), table_name='store_products')
    op.drop_index(op.f('ix_store_products_sku'), table_name='store_products')
    op.drop_index('ix_store_products_public_lookup', table_name='store_products')
    op.drop_index('ix_store_products_price', table_name='store_products')
    op.drop_index(op.f('ix_store_products_name'), table_name='store_products')
    op.drop_index(op.f('ix_store_products_is_featured'), table_name='store_products')
    op.drop_index(op.f('ix_store_products_is_active'), table_name='store_products')
    op.drop_index('ix_store_products_category_status', table_name='store_products')
    op.drop_index(op.f('ix_store_products_category_id'), table_name='store_products')
    op.drop_table('store_products')
    op.drop_index('ix_product_categories_sort', table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_slug'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_parent_id'), table_name='product_categories')
    op.drop_index('ix_product_categories_parent_active', table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_is_active'), table_name='product_categories')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
