"""add unified subscription entitlement foundation

Revision ID: 96f4165b43fe
Revises: 3af106b82c79
Create Date: 2026-07-26 00:35:09.177254

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "96f4165b43fe"
down_revision: str | Sequence[str] | None = "3af106b82c79"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_features",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("module", sa.String(length=60), nullable=False),
        sa.Column("value_kind", sa.String(length=20), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=True),
        sa.Column("is_metered", sa.Boolean(), nullable=False),
        sa.Column("is_safety_exempt", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("status IN ('active', 'retired')", name="ck_billing_features_status"),
        sa.CheckConstraint(
            "value_kind IN ('boolean', 'integer', 'decimal', 'string', 'json')",
            name="ck_billing_features_value_kind",
        ),
        sa.CheckConstraint(
            "is_safety_exempt = 0 OR is_metered = 0", name="ck_billing_features_safety_not_metered"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_billing_features_module"), "billing_features", ["module"], unique=False
    )
    op.create_index(
        "ix_billing_features_module_status", "billing_features", ["module", "status"], unique=False
    )
    op.create_index(
        op.f("ix_billing_features_status"), "billing_features", ["status"], unique=False
    )
    op.create_table(
        "billing_plans",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("billing_period", sa.String(length=20), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=True),
        sa.Column("price_toman", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("is_default_free", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.DateTime(), nullable=True),
        sa.Column("effective_until", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(billing_period = 'custom' AND duration_days > 0) OR (billing_period <> 'custom' AND duration_days IS NULL)",
            name="ck_billing_plans_custom_duration",
        ),
        sa.CheckConstraint(
            "(billing_period = 'free' AND price_toman = 0) OR billing_period <> 'free'",
            name="ck_billing_plans_free_price",
        ),
        sa.CheckConstraint(
            "billing_period IN ('free', 'monthly', 'yearly', 'custom')",
            name="ck_billing_plans_period",
        ),
        sa.CheckConstraint("currency = 'TOMAN'", name="ck_billing_plans_currency_toman"),
        sa.CheckConstraint(
            "is_default_free = 0 OR (billing_period = 'free' AND price_toman = 0)",
            name="ck_billing_plans_default_free",
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'retired')", name="ck_billing_plans_status"
        ),
        sa.CheckConstraint(
            "effective_until IS NULL OR effective_from IS NULL OR effective_until > effective_from",
            name="ck_billing_plans_effective_range",
        ),
        sa.CheckConstraint("price_toman >= 0", name="ck_billing_plans_price_nonnegative"),
        sa.CheckConstraint("version > 0", name="ck_billing_plans_version_positive"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", "version", name="uq_billing_plan_code_version"),
    )
    op.create_index(op.f("ix_billing_plans_status"), "billing_plans", ["status"], unique=False)
    op.create_index(
        "ix_billing_plans_status_period",
        "billing_plans",
        ["status", "billing_period"],
        unique=False,
    )
    op.create_table(
        "billing_plan_features",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("plan_id", sa.BigInteger(), nullable=False),
        sa.Column("feature_id", sa.BigInteger(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_unlimited", sa.Boolean(), nullable=False),
        sa.Column("boolean_value", sa.Boolean(), nullable=True),
        sa.Column("numeric_value", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("string_value", sa.String(length=500), nullable=True),
        sa.Column("json_value", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "is_unlimited = 0 OR numeric_value IS NULL",
            name="ck_billing_plan_features_unlimited_no_numeric",
        ),
        sa.CheckConstraint(
            "numeric_value IS NULL OR numeric_value >= 0",
            name="ck_billing_plan_features_numeric_nonnegative",
        ),
        sa.ForeignKeyConstraint(["feature_id"], ["billing_features.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["plan_id"], ["billing_plans.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "feature_id", name="uq_billing_plan_feature"),
    )
    op.create_index(
        op.f("ix_billing_plan_features_feature_id"),
        "billing_plan_features",
        ["feature_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_billing_plan_features_plan_id"), "billing_plan_features", ["plan_id"], unique=False
    )
    op.create_table(
        "billing_subscriptions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("plan_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("starts_at", sa.DateTime(), nullable=True),
        sa.Column("current_period_starts_at", sa.DateTime(), nullable=True),
        sa.Column("current_period_ends_at", sa.DateTime(), nullable=True),
        sa.Column("grace_ends_at", sa.DateTime(), nullable=True),
        sa.Column("auto_renew", sa.Boolean(), nullable=False),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("cancellation_reason", sa.String(length=500), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(status IN ('cancelled', 'expired') AND ended_at IS NOT NULL) OR (status NOT IN ('cancelled', 'expired') AND ended_at IS NULL)",
            name="ck_billing_subscriptions_end_state",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'active', 'grace', 'cancelled', 'expired')",
            name="ck_billing_subscriptions_status",
        ),
        sa.CheckConstraint(
            "cancelled_at IS NULL OR cancellation_reason IS NOT NULL",
            name="ck_billing_subscriptions_cancel_reason",
        ),
        sa.CheckConstraint(
            "current_period_ends_at IS NULL OR current_period_starts_at IS NULL OR current_period_ends_at > current_period_starts_at",
            name="ck_billing_subscriptions_period_range",
        ),
        sa.CheckConstraint(
            "grace_ends_at IS NULL OR current_period_ends_at IS NULL OR grace_ends_at >= current_period_ends_at",
            name="ck_billing_subscriptions_grace_range",
        ),
        sa.CheckConstraint("version > 0", name="ck_billing_subscriptions_version_positive"),
        sa.ForeignKeyConstraint(["plan_id"], ["billing_plans.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["auth_users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_billing_subscriptions_period_end",
        "billing_subscriptions",
        ["status", "current_period_ends_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_billing_subscriptions_plan_id"), "billing_subscriptions", ["plan_id"], unique=False
    )
    op.create_index(
        op.f("ix_billing_subscriptions_status"), "billing_subscriptions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_billing_subscriptions_user_id"), "billing_subscriptions", ["user_id"], unique=False
    )
    op.create_index(
        "ix_billing_subscriptions_user_status",
        "billing_subscriptions",
        ["user_id", "status"],
        unique=False,
    )
    op.create_table(
        "billing_subscription_periods",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("subscription_id", sa.BigInteger(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("starts_at", sa.DateTime(), nullable=False),
        sa.Column("ends_at", sa.DateTime(), nullable=False),
        sa.Column("invoice_id", sa.BigInteger(), nullable=True),
        sa.Column("plan_code_snapshot", sa.String(length=80), nullable=False),
        sa.Column("plan_version_snapshot", sa.Integer(), nullable=False),
        sa.Column("price_toman_snapshot", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("currency = 'TOMAN'", name="ck_billing_period_currency_toman"),
        sa.CheckConstraint(
            "status IN ('pending', 'active', 'closed', 'void')",
            name="ck_billing_subscription_period_status",
        ),
        sa.CheckConstraint("ends_at > starts_at", name="ck_billing_subscription_period_range"),
        sa.CheckConstraint("plan_version_snapshot > 0", name="ck_billing_period_plan_version"),
        sa.CheckConstraint("price_toman_snapshot >= 0", name="ck_billing_period_price_nonnegative"),
        sa.CheckConstraint("sequence > 0", name="ck_billing_subscription_period_sequence"),
        sa.ForeignKeyConstraint(
            ["invoice_id"], ["finance_billing_invoices.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["billing_subscriptions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invoice_id", name="uq_billing_subscription_period_invoice"),
        sa.UniqueConstraint(
            "subscription_id", "sequence", name="uq_billing_subscription_period_sequence"
        ),
    )
    op.create_index(
        "ix_billing_subscription_period_dates",
        "billing_subscription_periods",
        ["starts_at", "ends_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_billing_subscription_periods_invoice_id"),
        "billing_subscription_periods",
        ["invoice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_billing_subscription_periods_subscription_id"),
        "billing_subscription_periods",
        ["subscription_id"],
        unique=False,
    )
    op.create_table(
        "billing_entitlements",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("subscription_id", sa.BigInteger(), nullable=False),
        sa.Column("period_id", sa.BigInteger(), nullable=False),
        sa.Column("feature_id", sa.BigInteger(), nullable=False),
        sa.Column("feature_code_snapshot", sa.String(length=120), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_unlimited", sa.Boolean(), nullable=False),
        sa.Column("limit_value", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("policy_value", sa.JSON(), nullable=True),
        sa.Column("starts_at", sa.DateTime(), nullable=False),
        sa.Column("ends_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "source IN ('plan', 'addon', 'admin')", name="ck_billing_entitlements_source"
        ),
        sa.CheckConstraint("ends_at > starts_at", name="ck_billing_entitlements_range"),
        sa.CheckConstraint(
            "is_unlimited = 0 OR limit_value IS NULL",
            name="ck_billing_entitlements_unlimited_no_limit",
        ),
        sa.CheckConstraint(
            "limit_value IS NULL OR limit_value >= 0",
            name="ck_billing_entitlements_limit_nonnegative",
        ),
        sa.ForeignKeyConstraint(["feature_id"], ["billing_features.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["period_id"], ["billing_subscription_periods.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["billing_subscriptions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth_users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "period_id", "feature_id", name="uq_billing_entitlement_period_feature"
        ),
    )
    op.create_index(
        op.f("ix_billing_entitlements_feature_id"),
        "billing_entitlements",
        ["feature_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_billing_entitlements_period_id"),
        "billing_entitlements",
        ["period_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_billing_entitlements_subscription_id"),
        "billing_entitlements",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        "ix_billing_entitlements_user_feature",
        "billing_entitlements",
        ["user_id", "feature_code_snapshot"],
        unique=False,
    )
    op.create_index(
        op.f("ix_billing_entitlements_user_id"), "billing_entitlements", ["user_id"], unique=False
    )
    op.create_table(
        "billing_feature_usage",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("entitlement_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("period_id", sa.BigInteger(), nullable=False),
        sa.Column("feature_id", sa.BigInteger(), nullable=False),
        sa.Column("used_value", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("reserved_value", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("reserved_value >= 0", name="ck_billing_feature_usage_reserved"),
        sa.CheckConstraint("used_value >= 0", name="ck_billing_feature_usage_used"),
        sa.CheckConstraint("version > 0", name="ck_billing_feature_usage_version"),
        sa.ForeignKeyConstraint(
            ["entitlement_id"], ["billing_entitlements.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["feature_id"], ["billing_features.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["period_id"], ["billing_subscription_periods.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth_users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entitlement_id"),
        sa.UniqueConstraint(
            "user_id", "period_id", "feature_id", name="uq_billing_feature_usage_scope"
        ),
    )
    op.create_index(
        op.f("ix_billing_feature_usage_feature_id"),
        "billing_feature_usage",
        ["feature_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_billing_feature_usage_period_id"),
        "billing_feature_usage",
        ["period_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_billing_feature_usage_user_id"), "billing_feature_usage", ["user_id"], unique=False
    )
    op.create_index(
        "ix_billing_feature_usage_user_period",
        "billing_feature_usage",
        ["user_id", "period_id"],
        unique=False,
    )
    op.create_table(
        "billing_usage_reservations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("usage_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("feature_code_snapshot", sa.String(length=120), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("idempotency_key", sa.String(length=180), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("finalized_at", sa.DateTime(), nullable=True),
        sa.Column("released_at", sa.DateTime(), nullable=True),
        sa.Column("release_reason", sa.String(length=500), nullable=True),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(status = 'reserved' AND finalized_at IS NULL AND released_at IS NULL) OR (status = 'finalized' AND finalized_at IS NOT NULL AND released_at IS NULL) OR (status IN ('released', 'expired') AND finalized_at IS NULL AND released_at IS NOT NULL)",
            name="ck_billing_usage_reservation_terminal_state",
        ),
        sa.CheckConstraint(
            "status IN ('reserved', 'finalized', 'released', 'expired')",
            name="ck_billing_usage_reservation_status",
        ),
        sa.CheckConstraint("amount > 0", name="ck_billing_usage_reservation_amount"),
        sa.ForeignKeyConstraint(["usage_id"], ["billing_feature_usage.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["auth_users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_billing_usage_reservations_expires_at"),
        "billing_usage_reservations",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_billing_usage_reservations_expiry",
        "billing_usage_reservations",
        ["status", "expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_billing_usage_reservations_status"),
        "billing_usage_reservations",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_billing_usage_reservations_usage_id"),
        "billing_usage_reservations",
        ["usage_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_billing_usage_reservations_user_id"),
        "billing_usage_reservations",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # MySQL owns several generated FK-supporting indexes. Dropping the tables
    # in reverse dependency order safely removes their indexes and constraints.
    op.drop_table("billing_usage_reservations")
    op.drop_table("billing_feature_usage")
    op.drop_table("billing_entitlements")
    op.drop_table("billing_subscription_periods")
    op.drop_table("billing_subscriptions")
    op.drop_table("billing_plan_features")
    op.drop_table("billing_plans")
    op.drop_table("billing_features")
    return

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_billing_usage_reservations_user_id"), table_name="billing_usage_reservations"
    )
    op.drop_index(
        op.f("ix_billing_usage_reservations_usage_id"), table_name="billing_usage_reservations"
    )
    op.drop_index(
        op.f("ix_billing_usage_reservations_status"), table_name="billing_usage_reservations"
    )
    op.drop_index("ix_billing_usage_reservations_expiry", table_name="billing_usage_reservations")
    op.drop_index(
        op.f("ix_billing_usage_reservations_expires_at"), table_name="billing_usage_reservations"
    )
    op.drop_table("billing_usage_reservations")
    op.drop_index("ix_billing_feature_usage_user_period", table_name="billing_feature_usage")
    op.drop_index(op.f("ix_billing_feature_usage_user_id"), table_name="billing_feature_usage")
    op.drop_index(op.f("ix_billing_feature_usage_period_id"), table_name="billing_feature_usage")
    op.drop_index(op.f("ix_billing_feature_usage_feature_id"), table_name="billing_feature_usage")
    op.drop_table("billing_feature_usage")
    op.drop_index(op.f("ix_billing_entitlements_user_id"), table_name="billing_entitlements")
    op.drop_index("ix_billing_entitlements_user_feature", table_name="billing_entitlements")
    op.drop_index(
        op.f("ix_billing_entitlements_subscription_id"), table_name="billing_entitlements"
    )
    op.drop_index(op.f("ix_billing_entitlements_period_id"), table_name="billing_entitlements")
    op.drop_index(op.f("ix_billing_entitlements_feature_id"), table_name="billing_entitlements")
    op.drop_table("billing_entitlements")
    op.drop_index(
        op.f("ix_billing_subscription_periods_subscription_id"),
        table_name="billing_subscription_periods",
    )
    op.drop_index(
        op.f("ix_billing_subscription_periods_invoice_id"),
        table_name="billing_subscription_periods",
    )
    op.drop_index("ix_billing_subscription_period_dates", table_name="billing_subscription_periods")
    op.drop_table("billing_subscription_periods")
    op.drop_index("ix_billing_subscriptions_user_status", table_name="billing_subscriptions")
    op.drop_index(op.f("ix_billing_subscriptions_user_id"), table_name="billing_subscriptions")
    op.drop_index(op.f("ix_billing_subscriptions_status"), table_name="billing_subscriptions")
    op.drop_index(op.f("ix_billing_subscriptions_plan_id"), table_name="billing_subscriptions")
    op.drop_index("ix_billing_subscriptions_period_end", table_name="billing_subscriptions")
    op.drop_table("billing_subscriptions")
    op.drop_index(op.f("ix_billing_plan_features_plan_id"), table_name="billing_plan_features")
    op.drop_index(op.f("ix_billing_plan_features_feature_id"), table_name="billing_plan_features")
    op.drop_table("billing_plan_features")
    op.drop_index("ix_billing_plans_status_period", table_name="billing_plans")
    op.drop_index(op.f("ix_billing_plans_status"), table_name="billing_plans")
    op.drop_table("billing_plans")
    op.drop_index(op.f("ix_billing_features_status"), table_name="billing_features")
    op.drop_index("ix_billing_features_module_status", table_name="billing_features")
    op.drop_index(op.f("ix_billing_features_module"), table_name="billing_features")
    op.drop_table("billing_features")
    # ### end Alembic commands ###
