"""add Barzegar knowledge governance

Revision ID: b21d5c93b7f1
Revises: a21c4b82a6e0
Create Date: 2026-07-27 19:02:05.137604

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "b21d5c93b7f1"
down_revision: str | Sequence[str] | None = "a21c4b82a6e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_knowledge_sources",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("publisher", sa.String(length=250), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("license_code", sa.String(length=80), nullable=False),
        sa.Column("license_evidence", sa.String(length=1000), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by_user_id", sa.BigInteger(), nullable=False),
        sa.Column("reviewed_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column("review_reason", sa.String(length=1000), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(status IN ('draft','in_review') AND reviewed_at IS NULL) OR (status IN ('approved','rejected','withdrawn') AND reviewed_at IS NOT NULL AND reviewed_by_user_id IS NOT NULL)",
            name="ck_ai_knowledge_sources_review_state",
        ),
        sa.CheckConstraint(
            "status IN ('draft','in_review','approved','rejected','withdrawn')",
            name="ck_ai_knowledge_sources_status",
        ),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["auth_users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reviewed_by_user_id"], ["auth_users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_ai_knowledge_sources_status"), "ai_knowledge_sources", ["status"], unique=False
    )
    op.create_table(
        "ai_knowledge_source_versions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("edition", sa.String(length=120), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("effective_from", sa.DateTime(), nullable=True),
        sa.Column("effective_until", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("approved_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("withdrawal_reason", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(status = 'approved' AND approved_by_user_id IS NOT NULL AND approved_at IS NOT NULL) OR status <> 'approved'",
            name="ck_ai_source_versions_approval",
        ),
        sa.CheckConstraint(
            "status IN ('draft','in_review','approved','rejected','withdrawn')",
            name="ck_ai_source_versions_status",
        ),
        sa.CheckConstraint(
            "effective_until IS NULL OR effective_from IS NOT NULL AND effective_until > effective_from",
            name="ck_ai_source_versions_effective_range",
        ),
        sa.CheckConstraint("version_no > 0", name="ck_ai_source_version_positive"),
        sa.ForeignKeyConstraint(["approved_by_user_id"], ["auth_users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_id"], ["ai_knowledge_sources.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "version_no", name="uq_ai_source_version_no"),
    )
    op.create_index(
        op.f("ix_ai_knowledge_source_versions_status"),
        "ai_knowledge_source_versions",
        ["status"],
        unique=False,
    )
    op.create_table(
        "ai_knowledge_documents",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_version_id", sa.BigInteger(), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("storage_key", sa.String(length=1000), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("is_encrypted", sa.Boolean(), nullable=False),
        sa.Column("extraction_status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "extraction_status IN ('pending','running','succeeded','needs_review','failed')",
            name="ck_ai_documents_extraction_status",
        ),
        sa.CheckConstraint("mime_type = 'application/pdf'", name="ck_ai_documents_pdf_only"),
        sa.CheckConstraint("byte_size > 0", name="ck_ai_documents_byte_size"),
        sa.CheckConstraint(
            "page_count IS NULL OR page_count > 0", name="ck_ai_documents_page_count"
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"], ["ai_knowledge_source_versions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256"),
    )
    op.create_index(
        op.f("ix_ai_knowledge_documents_extraction_status"),
        "ai_knowledge_documents",
        ["extraction_status"],
        unique=False,
    )
    op.create_table(
        "ai_knowledge_ingestion_jobs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.BigInteger(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=180), nullable=False),
        sa.Column("extractor_version", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("pages_processed", sa.Integer(), nullable=False),
        sa.Column("extracted_characters", sa.Integer(), nullable=False),
        sa.Column("quality_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending','running','succeeded','needs_review','failed')",
            name="ck_ai_ingestion_jobs_status",
        ),
        sa.CheckConstraint(
            "pages_processed >= 0 AND extracted_characters >= 0", name="ck_ai_ingestion_jobs_counts"
        ),
        sa.CheckConstraint(
            "quality_score IS NULL OR quality_score BETWEEN 0 AND 1",
            name="ck_ai_ingestion_jobs_quality",
        ),
        sa.CheckConstraint(
            "(status = 'pending' AND started_at IS NULL AND completed_at IS NULL) OR (status = 'running' AND started_at IS NOT NULL AND completed_at IS NULL) OR (status IN ('succeeded','needs_review','failed') AND started_at IS NOT NULL AND completed_at IS NOT NULL)",
            name="ck_ai_ingestion_jobs_lifecycle",
        ),
        sa.CheckConstraint(
            "(status = 'failed' AND failure_code IS NOT NULL) OR (status <> 'failed' AND failure_code IS NULL)",
            name="ck_ai_ingestion_jobs_failure",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["ai_knowledge_documents.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_table(
        "ai_knowledge_extracted_pages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ingestion_job_id", sa.BigInteger(), nullable=False),
        sa.Column("document_id", sa.BigInteger(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("extracted_text", sa.Text(), nullable=False),
        sa.Column("text_sha256", sa.String(length=64), nullable=False),
        sa.Column("character_count", sa.Integer(), nullable=False),
        sa.Column("quality_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "character_count = CHAR_LENGTH(extracted_text)",
            name="ck_ai_extracted_pages_character_count",
        ),
        sa.CheckConstraint("page_number > 0", name="ck_ai_extracted_pages_number"),
        sa.CheckConstraint("quality_score BETWEEN 0 AND 1", name="ck_ai_extracted_pages_quality"),
        sa.ForeignKeyConstraint(
            ["document_id"], ["ai_knowledge_documents.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_job_id"], ["ai_knowledge_ingestion_jobs.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ingestion_job_id", "page_number", name="uq_ai_extracted_page_job_number"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ai_knowledge_extracted_pages")
    op.drop_table("ai_knowledge_ingestion_jobs")
    op.drop_index(
        op.f("ix_ai_knowledge_documents_extraction_status"), table_name="ai_knowledge_documents"
    )
    op.drop_table("ai_knowledge_documents")
    op.drop_index(
        op.f("ix_ai_knowledge_source_versions_status"), table_name="ai_knowledge_source_versions"
    )
    op.drop_table("ai_knowledge_source_versions")
    op.drop_index(op.f("ix_ai_knowledge_sources_status"), table_name="ai_knowledge_sources")
    op.drop_table("ai_knowledge_sources")
    # ### end Alembic commands ###
