"""add Barzegar retrieval and citations

Revision ID: c21e6d04c8a2
Revises: b21d5c93b7f1
Create Date: 2026-07-27 19:15:11.935157

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "c21e6d04c8a2"
down_revision: str | Sequence[str] | None = "b21d5c93b7f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_embedding_models",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("model_key", sa.String(length=120), nullable=False),
        sa.Column("model_version", sa.String(length=80), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column("distance_metric", sa.String(length=20), nullable=False),
        sa.Column("normalization", sa.String(length=30), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("active_scope", sa.String(length=30), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "distance_metric IN ('cosine','dot','euclidean')", name="ck_ai_embedding_distance"
        ),
        sa.CheckConstraint("normalization IN ('none','l2')", name="ck_ai_embedding_normalization"),
        sa.CheckConstraint("dimensions BETWEEN 8 AND 65536", name="ck_ai_embedding_dimensions"),
        sa.CheckConstraint(
            "(is_active = 1 AND active_scope = 'global') OR (is_active = 0 AND active_scope IS NULL)",
            name="ck_ai_embedding_active_scope",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("active_scope"),
        sa.UniqueConstraint("model_key", "model_version", name="uq_ai_embedding_model_version"),
    )
    op.create_index(
        op.f("ix_ai_embedding_models_is_active"), "ai_embedding_models", ["is_active"], unique=False
    )
    op.create_table(
        "ai_knowledge_chunks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_version_id", sa.BigInteger(), nullable=False),
        sa.Column("document_id", sa.BigInteger(), nullable=False),
        sa.Column("extracted_page_id", sa.BigInteger(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("character_start", sa.Integer(), nullable=False),
        sa.Column("character_end", sa.Integer(), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("text_sha256", sa.String(length=64), nullable=False),
        sa.Column("chunker_version", sa.String(length=80), nullable=False),
        sa.Column("token_estimate", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "CHAR_LENGTH(chunk_text) = character_end - character_start",
            name="ck_ai_chunks_character_count",
        ),
        sa.CheckConstraint(
            "character_start >= 0 AND character_end > character_start",
            name="ck_ai_chunks_character_range",
        ),
        sa.CheckConstraint("chunk_index >= 0", name="ck_ai_chunks_index"),
        sa.CheckConstraint("page_number > 0", name="ck_ai_chunks_page_number"),
        sa.CheckConstraint("token_estimate > 0", name="ck_ai_chunks_token_estimate"),
        sa.ForeignKeyConstraint(
            ["document_id"], ["ai_knowledge_documents.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["extracted_page_id"], ["ai_knowledge_extracted_pages.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"], ["ai_knowledge_source_versions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "extracted_page_id",
            "chunker_version",
            "chunk_index",
            name="uq_ai_chunk_page_version_index",
        ),
    )
    op.create_index(
        "ix_ai_chunks_document_page_active",
        "ai_knowledge_chunks",
        ["document_id", "page_number", "is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_knowledge_chunks_document_id"),
        "ai_knowledge_chunks",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_knowledge_chunks_extracted_page_id"),
        "ai_knowledge_chunks",
        ["extracted_page_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_knowledge_chunks_is_active"), "ai_knowledge_chunks", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_ai_knowledge_chunks_source_version_id"),
        "ai_knowledge_chunks",
        ["source_version_id"],
        unique=False,
    )
    op.create_table(
        "ai_embedding_index_records",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("chunk_id", sa.BigInteger(), nullable=False),
        sa.Column("embedding_model_id", sa.BigInteger(), nullable=False),
        sa.Column("store_key", sa.String(length=80), nullable=False),
        sa.Column("collection_name", sa.String(length=160), nullable=False),
        sa.Column("point_id", sa.String(length=180), nullable=False),
        sa.Column("vector_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("indexed_at", sa.DateTime(), nullable=True),
        sa.Column("removed_at", sa.DateTime(), nullable=True),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(status = 'pending' AND indexed_at IS NULL AND removed_at IS NULL AND failure_code IS NULL) OR (status = 'indexed' AND indexed_at IS NOT NULL AND removed_at IS NULL AND failure_code IS NULL) OR (status = 'failed' AND failure_code IS NOT NULL) OR (status = 'removed' AND indexed_at IS NOT NULL AND removed_at IS NOT NULL)",
            name="ck_ai_embedding_index_lifecycle",
        ),
        sa.CheckConstraint(
            "status IN ('pending','indexed','failed','removed')",
            name="ck_ai_embedding_index_status",
        ),
        sa.ForeignKeyConstraint(["chunk_id"], ["ai_knowledge_chunks.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["embedding_model_id"], ["ai_embedding_models.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chunk_id", "embedding_model_id", name="uq_ai_embedding_chunk_model"),
        sa.UniqueConstraint(
            "store_key", "collection_name", "point_id", name="uq_ai_embedding_store_point"
        ),
    )
    op.create_index(
        op.f("ix_ai_embedding_index_records_chunk_id"),
        "ai_embedding_index_records",
        ["chunk_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_embedding_index_records_embedding_model_id"),
        "ai_embedding_index_records",
        ["embedding_model_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_embedding_index_records_status"),
        "ai_embedding_index_records",
        ["status"],
        unique=False,
    )
    op.create_table(
        "ai_response_citations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("chunk_id", sa.BigInteger(), nullable=False),
        sa.Column("citation_order", sa.Integer(), nullable=False),
        sa.Column("quoted_text", sa.Text(), nullable=False),
        sa.Column("quoted_text_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_title_snapshot", sa.String(length=250), nullable=False),
        sa.Column("source_version_snapshot", sa.String(length=120), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("retrieval_score", sa.Numeric(precision=8, scale=7), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("CHAR_LENGTH(quoted_text) > 0", name="ck_ai_citation_quote_nonempty"),
        sa.CheckConstraint("citation_order > 0", name="ck_ai_citation_order"),
        sa.CheckConstraint("page_number > 0", name="ck_ai_citation_page"),
        sa.CheckConstraint(
            "retrieval_score IS NULL OR retrieval_score BETWEEN 0 AND 1",
            name="ck_ai_citation_score",
        ),
        sa.ForeignKeyConstraint(["chunk_id"], ["ai_knowledge_chunks.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["message_id"], ["ai_messages.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id", "chunk_id", name="uq_ai_citation_message_chunk"),
        sa.UniqueConstraint("message_id", "citation_order", name="uq_ai_citation_message_order"),
    )
    op.create_index(
        op.f("ix_ai_response_citations_chunk_id"),
        "ai_response_citations",
        ["chunk_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_response_citations_message_id"),
        "ai_response_citations",
        ["message_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ai_response_citations_message_id"), table_name="ai_response_citations")
    op.drop_index(op.f("ix_ai_response_citations_chunk_id"), table_name="ai_response_citations")
    op.drop_table("ai_response_citations")
    op.drop_index(
        op.f("ix_ai_embedding_index_records_status"), table_name="ai_embedding_index_records"
    )
    op.drop_index(
        op.f("ix_ai_embedding_index_records_embedding_model_id"),
        table_name="ai_embedding_index_records",
    )
    op.drop_index(
        op.f("ix_ai_embedding_index_records_chunk_id"), table_name="ai_embedding_index_records"
    )
    op.drop_table("ai_embedding_index_records")
    op.drop_index(
        op.f("ix_ai_knowledge_chunks_source_version_id"), table_name="ai_knowledge_chunks"
    )
    op.drop_index(op.f("ix_ai_knowledge_chunks_is_active"), table_name="ai_knowledge_chunks")
    op.drop_index(
        op.f("ix_ai_knowledge_chunks_extracted_page_id"), table_name="ai_knowledge_chunks"
    )
    op.drop_index(op.f("ix_ai_knowledge_chunks_document_id"), table_name="ai_knowledge_chunks")
    op.drop_index("ix_ai_chunks_document_page_active", table_name="ai_knowledge_chunks")
    op.drop_table("ai_knowledge_chunks")
    op.drop_index(op.f("ix_ai_embedding_models_is_active"), table_name="ai_embedding_models")
    op.drop_table("ai_embedding_models")
    # ### end Alembic commands ###
