"""harden Barzegar async request workflow

Revision ID: d21f7e15d9b3
Revises: c21e6d04c8a2
Create Date: 2026-07-27 19:27:02.426387

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "d21f7e15d9b3"
down_revision: str | Sequence[str] | None = "c21e6d04c8a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_messages", sa.Column("request_message_kind", sa.String(length=20), nullable=True)
    )
    op.create_unique_constraint(
        "uq_ai_message_request_kind", "ai_messages", ["request_id", "request_message_kind"]
    )
    op.create_check_constraint(
        "ck_ai_messages_request_kind",
        "ai_messages",
        "(request_message_kind IS NULL) OR "
        "(request_message_kind = 'input' AND role = 'user' AND request_id IS NOT NULL) OR "
        "(request_message_kind = 'output' AND role = 'assistant' AND request_id IS NOT NULL)",
    )
    op.add_column(
        "ai_requests", sa.Column("request_fingerprint", sa.String(length=64), nullable=True)
    )
    op.add_column("ai_requests", sa.Column("next_attempt_at", sa.DateTime(), nullable=True))
    op.add_column(
        "ai_requests", sa.Column("attempt_count", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        "ai_requests", sa.Column("max_attempts", sa.Integer(), nullable=False, server_default="3")
    )
    op.add_column("ai_requests", sa.Column("locked_by", sa.String(length=120), nullable=True))
    op.add_column("ai_requests", sa.Column("lease_expires_at", sa.DateTime(), nullable=True))
    op.execute(
        "UPDATE ai_requests SET request_fingerprint = "
        "SHA2(CONCAT('legacy:', id, ':', idempotency_key), 256), "
        "next_attempt_at = requested_at"
    )
    op.alter_column(
        "ai_requests",
        "request_fingerprint",
        existing_type=sa.String(length=64),
        nullable=False,
    )
    op.alter_column(
        "ai_requests",
        "next_attempt_at",
        existing_type=sa.DateTime(),
        nullable=False,
    )
    op.alter_column(
        "ai_requests",
        "attempt_count",
        existing_type=sa.Integer(),
        existing_nullable=False,
        server_default=None,
    )
    op.alter_column(
        "ai_requests",
        "max_attempts",
        existing_type=sa.Integer(),
        existing_nullable=False,
        server_default=None,
    )
    op.create_check_constraint(
        "ck_ai_requests_attempts",
        "ai_requests",
        "attempt_count >= 0 AND max_attempts BETWEEN 1 AND 10 AND attempt_count <= max_attempts",
    )
    op.create_check_constraint(
        "ck_ai_requests_lease",
        "ai_requests",
        "(status = 'running' AND locked_by IS NOT NULL AND lease_expires_at IS NOT NULL) OR "
        "(status <> 'running' AND locked_by IS NULL AND lease_expires_at IS NULL)",
    )
    op.create_index(
        op.f("ix_ai_requests_lease_expires_at"), "ai_requests", ["lease_expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_ai_requests_next_attempt_at"), "ai_requests", ["next_attempt_at"], unique=False
    )
    op.create_index(
        "ix_ai_requests_queue",
        "ai_requests",
        ["status", "next_attempt_at", "processing_priority"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ai_requests_queue", table_name="ai_requests")
    op.drop_index(op.f("ix_ai_requests_next_attempt_at"), table_name="ai_requests")
    op.drop_index(op.f("ix_ai_requests_lease_expires_at"), table_name="ai_requests")
    op.drop_constraint("ck_ai_requests_lease", "ai_requests", type_="check")
    op.drop_constraint("ck_ai_requests_attempts", "ai_requests", type_="check")
    op.drop_column("ai_requests", "lease_expires_at")
    op.drop_column("ai_requests", "locked_by")
    op.drop_column("ai_requests", "max_attempts")
    op.drop_column("ai_requests", "attempt_count")
    op.drop_column("ai_requests", "next_attempt_at")
    op.drop_column("ai_requests", "request_fingerprint")
    op.drop_constraint("uq_ai_message_request_kind", "ai_messages", type_="unique")
    op.drop_constraint("ck_ai_messages_request_kind", "ai_messages", type_="check")
    op.drop_column("ai_messages", "request_message_kind")
    # ### end Alembic commands ###
