"""harden Barzegar selected farm consent

Revision ID: e21a8f26e0c4
Revises: d21f7e15d9b3
Create Date: 2026-07-27 19:40:01.606460

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "e21a8f26e0c4"
down_revision: str | Sequence[str] | None = "d21f7e15d9b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_context_consents", sa.Column("idempotency_key", sa.String(length=180), nullable=True)
    )
    op.add_column(
        "ai_context_consents",
        sa.Column("selection_fingerprint", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "ai_context_consents", sa.Column("active_scope", sa.String(length=64), nullable=True)
    )
    op.get_bind().exec_driver_sql(
        "UPDATE ai_context_consents SET "
        "idempotency_key = CONCAT('legacy-consent-', id), "
        "selection_fingerprint = SHA2(CONCAT(user_id, ':', farm_id, ':', "
        "COALESCE(plot_id, 'none'), ':', COALESCE(crop_cycle_id, 'none'), ':', "
        "purpose, ':barzegar-farm-context-v1'), 256)"
    )
    op.get_bind().exec_driver_sql(
        "UPDATE ai_context_consents c JOIN ("
        "SELECT selection_fingerprint, MAX(id) AS keep_id "
        "FROM ai_context_consents WHERE status = 'active' "
        "GROUP BY selection_fingerprint"
        ") k ON k.selection_fingerprint = c.selection_fingerprint "
        "SET c.status = 'expired' "
        "WHERE c.status = 'active' AND c.id <> k.keep_id"
    )
    op.get_bind().exec_driver_sql(
        "UPDATE ai_context_consents SET active_scope = selection_fingerprint "
        "WHERE status = 'active'"
    )
    op.alter_column(
        "ai_context_consents",
        "idempotency_key",
        existing_type=sa.String(length=180),
        nullable=False,
    )
    op.alter_column(
        "ai_context_consents",
        "selection_fingerprint",
        existing_type=sa.String(length=64),
        nullable=False,
    )
    op.create_unique_constraint(
        "uq_ai_context_user_idempotency", "ai_context_consents", ["user_id", "idempotency_key"]
    )
    op.create_unique_constraint(
        "uq_ai_context_active_scope", "ai_context_consents", ["active_scope"]
    )
    op.create_check_constraint(
        "ck_ai_context_consents_active_scope",
        "ai_context_consents",
        "(status = 'active' AND active_scope IS NOT NULL) OR "
        "(status <> 'active' AND active_scope IS NULL)",
    )
    op.create_check_constraint(
        "ck_ai_context_consents_cycle_requires_plot",
        "ai_context_consents",
        "crop_cycle_id IS NULL OR plot_id IS NOT NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_ai_context_consents_cycle_requires_plot", "ai_context_consents", type_="check"
    )
    op.drop_constraint("ck_ai_context_consents_active_scope", "ai_context_consents", type_="check")
    op.drop_constraint("uq_ai_context_active_scope", "ai_context_consents", type_="unique")
    op.drop_constraint("uq_ai_context_user_idempotency", "ai_context_consents", type_="unique")
    op.drop_column("ai_context_consents", "active_scope")
    op.drop_column("ai_context_consents", "selection_fingerprint")
    op.drop_column("ai_context_consents", "idempotency_key")
    # ### end Alembic commands ###
