"""add geo tables

Revision ID: e28c2056fa9d
Revises: f1fe081114b3
Create Date: 2026-05-11 14:03:40.826918

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e28c2056fa9d'
down_revision: str | Sequence[str] | None = 'f1fe081114b3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_provinces',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('amar_code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_provinces_amar_code'), 'geo_provinces', ['amar_code'], unique=True)
    op.create_index(op.f('ix_geo_provinces_name'), 'geo_provinces', ['name'], unique=False)
    op.create_table('geo_counties',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('province_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('amar_code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['geo_provinces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_counties_amar_code'), 'geo_counties', ['amar_code'], unique=True)
    op.create_index(op.f('ix_geo_counties_name'), 'geo_counties', ['name'], unique=False)
    op.create_index(op.f('ix_geo_counties_province_id'), 'geo_counties', ['province_id'], unique=False)
    op.create_index('ix_geo_counties_province_name', 'geo_counties', ['province_id', 'name'], unique=False)
    op.create_table('geo_districts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('province_id', sa.BigInteger(), nullable=False),
    sa.Column('county_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('amar_code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['geo_counties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['province_id'], ['geo_provinces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_districts_amar_code'), 'geo_districts', ['amar_code'], unique=True)
    op.create_index(op.f('ix_geo_districts_county_id'), 'geo_districts', ['county_id'], unique=False)
    op.create_index('ix_geo_districts_county_name', 'geo_districts', ['county_id', 'name'], unique=False)
    op.create_index(op.f('ix_geo_districts_name'), 'geo_districts', ['name'], unique=False)
    op.create_index(op.f('ix_geo_districts_province_id'), 'geo_districts', ['province_id'], unique=False)
    op.create_table('geo_cities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('province_id', sa.BigInteger(), nullable=False),
    sa.Column('county_id', sa.BigInteger(), nullable=False),
    sa.Column('district_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('city_type', sa.String(length=80), nullable=True),
    sa.Column('amar_code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['geo_counties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['district_id'], ['geo_districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['province_id'], ['geo_provinces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_cities_amar_code'), 'geo_cities', ['amar_code'], unique=True)
    op.create_index(op.f('ix_geo_cities_county_id'), 'geo_cities', ['county_id'], unique=False)
    op.create_index('ix_geo_cities_county_name', 'geo_cities', ['county_id', 'name'], unique=False)
    op.create_index(op.f('ix_geo_cities_district_id'), 'geo_cities', ['district_id'], unique=False)
    op.create_index(op.f('ix_geo_cities_name'), 'geo_cities', ['name'], unique=False)
    op.create_index(op.f('ix_geo_cities_province_id'), 'geo_cities', ['province_id'], unique=False)
    op.create_index('ix_geo_cities_province_name', 'geo_cities', ['province_id', 'name'], unique=False)
    op.create_table('geo_rural_districts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('province_id', sa.BigInteger(), nullable=False),
    sa.Column('county_id', sa.BigInteger(), nullable=False),
    sa.Column('district_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('amar_code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['geo_counties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['district_id'], ['geo_districts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['province_id'], ['geo_provinces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_rural_districts_amar_code'), 'geo_rural_districts', ['amar_code'], unique=True)
    op.create_index(op.f('ix_geo_rural_districts_county_id'), 'geo_rural_districts', ['county_id'], unique=False)
    op.create_index(op.f('ix_geo_rural_districts_district_id'), 'geo_rural_districts', ['district_id'], unique=False)
    op.create_index('ix_geo_rural_districts_district_name', 'geo_rural_districts', ['district_id', 'name'], unique=False)
    op.create_index(op.f('ix_geo_rural_districts_name'), 'geo_rural_districts', ['name'], unique=False)
    op.create_index(op.f('ix_geo_rural_districts_province_id'), 'geo_rural_districts', ['province_id'], unique=False)
    op.create_table('geo_villages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('province_id', sa.BigInteger(), nullable=False),
    sa.Column('county_id', sa.BigInteger(), nullable=False),
    sa.Column('district_id', sa.BigInteger(), nullable=True),
    sa.Column('rural_district_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('village_type', sa.String(length=80), nullable=True),
    sa.Column('diag', sa.String(length=100), nullable=True),
    sa.Column('amar_code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['geo_counties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['district_id'], ['geo_districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['province_id'], ['geo_provinces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rural_district_id'], ['geo_rural_districts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_villages_amar_code'), 'geo_villages', ['amar_code'], unique=True)
    op.create_index(op.f('ix_geo_villages_county_id'), 'geo_villages', ['county_id'], unique=False)
    op.create_index('ix_geo_villages_county_name', 'geo_villages', ['county_id', 'name'], unique=False)
    op.create_index(op.f('ix_geo_villages_district_id'), 'geo_villages', ['district_id'], unique=False)
    op.create_index(op.f('ix_geo_villages_name'), 'geo_villages', ['name'], unique=False)
    op.create_index(op.f('ix_geo_villages_province_id'), 'geo_villages', ['province_id'], unique=False)
    op.create_index(op.f('ix_geo_villages_rural_district_id'), 'geo_villages', ['rural_district_id'], unique=False)
    op.create_index('ix_geo_villages_rural_district_name', 'geo_villages', ['rural_district_id', 'name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_geo_villages_rural_district_name', table_name='geo_villages')
    op.drop_index(op.f('ix_geo_villages_rural_district_id'), table_name='geo_villages')
    op.drop_index(op.f('ix_geo_villages_province_id'), table_name='geo_villages')
    op.drop_index(op.f('ix_geo_villages_name'), table_name='geo_villages')
    op.drop_index(op.f('ix_geo_villages_district_id'), table_name='geo_villages')
    op.drop_index('ix_geo_villages_county_name', table_name='geo_villages')
    op.drop_index(op.f('ix_geo_villages_county_id'), table_name='geo_villages')
    op.drop_index(op.f('ix_geo_villages_amar_code'), table_name='geo_villages')
    op.drop_table('geo_villages')
    op.drop_index(op.f('ix_geo_rural_districts_province_id'), table_name='geo_rural_districts')
    op.drop_index(op.f('ix_geo_rural_districts_name'), table_name='geo_rural_districts')
    op.drop_index('ix_geo_rural_districts_district_name', table_name='geo_rural_districts')
    op.drop_index(op.f('ix_geo_rural_districts_district_id'), table_name='geo_rural_districts')
    op.drop_index(op.f('ix_geo_rural_districts_county_id'), table_name='geo_rural_districts')
    op.drop_index(op.f('ix_geo_rural_districts_amar_code'), table_name='geo_rural_districts')
    op.drop_table('geo_rural_districts')
    op.drop_index('ix_geo_cities_province_name', table_name='geo_cities')
    op.drop_index(op.f('ix_geo_cities_province_id'), table_name='geo_cities')
    op.drop_index(op.f('ix_geo_cities_name'), table_name='geo_cities')
    op.drop_index(op.f('ix_geo_cities_district_id'), table_name='geo_cities')
    op.drop_index('ix_geo_cities_county_name', table_name='geo_cities')
    op.drop_index(op.f('ix_geo_cities_county_id'), table_name='geo_cities')
    op.drop_index(op.f('ix_geo_cities_amar_code'), table_name='geo_cities')
    op.drop_table('geo_cities')
    op.drop_index(op.f('ix_geo_districts_province_id'), table_name='geo_districts')
    op.drop_index(op.f('ix_geo_districts_name'), table_name='geo_districts')
    op.drop_index('ix_geo_districts_county_name', table_name='geo_districts')
    op.drop_index(op.f('ix_geo_districts_county_id'), table_name='geo_districts')
    op.drop_index(op.f('ix_geo_districts_amar_code'), table_name='geo_districts')
    op.drop_table('geo_districts')
    op.drop_index('ix_geo_counties_province_name', table_name='geo_counties')
    op.drop_index(op.f('ix_geo_counties_province_id'), table_name='geo_counties')
    op.drop_index(op.f('ix_geo_counties_name'), table_name='geo_counties')
    op.drop_index(op.f('ix_geo_counties_amar_code'), table_name='geo_counties')
    op.drop_table('geo_counties')
    op.drop_index(op.f('ix_geo_provinces_name'), table_name='geo_provinces')
    op.drop_index(op.f('ix_geo_provinces_amar_code'), table_name='geo_provinces')
    op.drop_table('geo_provinces')
    # ### end Alembic commands ###
