"""add social tables

Revision ID: e35a7d8c4545
Revises: 42b49a30fc87
Create Date: 2026-05-26 12:43:35.054351

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e35a7d8c4545'
down_revision: str | Sequence[str] | None = '42b49a30fc87'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_social_categories_active_sort', 'social_categories', ['is_active', 'sort_order'], unique=False)
    op.create_table('social_posts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('author_user_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('post_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('visibility', sa.String(length=40), nullable=False),
    sa.Column('media_file_id', sa.BigInteger(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('province_id', sa.BigInteger(), nullable=True),
    sa.Column('city_id', sa.BigInteger(), nullable=True),
    sa.Column('village_id', sa.BigInteger(), nullable=True),
    sa.Column('province_name', sa.String(length=120), nullable=True),
    sa.Column('city_name', sa.String(length=120), nullable=True),
    sa.Column('village_name', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.String(length=40), nullable=True),
    sa.Column('longitude', sa.String(length=40), nullable=True),
    sa.Column('views_count', sa.BigInteger(), nullable=False),
    sa.Column('comments_count', sa.BigInteger(), nullable=False),
    sa.Column('reactions_count', sa.BigInteger(), nullable=False),
    sa.Column('reports_count', sa.BigInteger(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['social_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_posts_author_user_id'), 'social_posts', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_social_posts_category_id'), 'social_posts', ['category_id'], unique=False)
    op.create_index('ix_social_posts_category_status_created', 'social_posts', ['category_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_social_posts_city_id'), 'social_posts', ['city_id'], unique=False)
    op.create_index(op.f('ix_social_posts_country_code'), 'social_posts', ['country_code'], unique=False)
    op.create_index('ix_social_posts_geo', 'social_posts', ['province_id', 'city_id', 'village_id'], unique=False)
    op.create_index(op.f('ix_social_posts_media_file_id'), 'social_posts', ['media_file_id'], unique=False)
    op.create_index(op.f('ix_social_posts_province_id'), 'social_posts', ['province_id'], unique=False)
    op.create_index('ix_social_posts_status_created', 'social_posts', ['status', 'created_at'], unique=False)
    op.create_index('ix_social_posts_type_status_created', 'social_posts', ['post_type', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_social_posts_village_id'), 'social_posts', ['village_id'], unique=False)
    op.create_table('social_bookmarks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_social_bookmarks_post_user')
    )
    op.create_index(op.f('ix_social_bookmarks_post_id'), 'social_bookmarks', ['post_id'], unique=False)
    op.create_index('ix_social_bookmarks_user_created', 'social_bookmarks', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_social_bookmarks_user_id'), 'social_bookmarks', ['user_id'], unique=False)
    op.create_table('social_comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('author_user_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_comment_id', sa.BigInteger(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('reactions_count', sa.BigInteger(), nullable=False),
    sa.Column('reports_count', sa.BigInteger(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['social_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_comments_author_user_id'), 'social_comments', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_social_comments_parent_comment_id'), 'social_comments', ['parent_comment_id'], unique=False)
    op.create_index('ix_social_comments_parent_created', 'social_comments', ['parent_comment_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_social_comments_post_id'), 'social_comments', ['post_id'], unique=False)
    op.create_index('ix_social_comments_post_status_created', 'social_comments', ['post_id', 'status', 'created_at'], unique=False)
    op.create_table('social_moderation_actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('moderator_user_id', sa.BigInteger(), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=True),
    sa.Column('comment_id', sa.BigInteger(), nullable=True),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['social_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moderator_user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_moderation_actions_comment_id'), 'social_moderation_actions', ['comment_id'], unique=False)
    op.create_index(op.f('ix_social_moderation_actions_moderator_user_id'), 'social_moderation_actions', ['moderator_user_id'], unique=False)
    op.create_index(op.f('ix_social_moderation_actions_post_id'), 'social_moderation_actions', ['post_id'], unique=False)
    op.create_index('ix_social_moderation_moderator_created', 'social_moderation_actions', ['moderator_user_id', 'created_at'], unique=False)
    op.create_index('ix_social_moderation_target_created', 'social_moderation_actions', ['target_type', 'created_at'], unique=False)
    op.create_table('social_reactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=True),
    sa.Column('comment_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reaction_type', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['social_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'comment_id', 'user_id', 'reaction_type', name='uq_social_reactions_target_user_type')
    )
    op.create_index(op.f('ix_social_reactions_comment_id'), 'social_reactions', ['comment_id'], unique=False)
    op.create_index(op.f('ix_social_reactions_post_id'), 'social_reactions', ['post_id'], unique=False)
    op.create_index('ix_social_reactions_user_created', 'social_reactions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_social_reactions_user_id'), 'social_reactions', ['user_id'], unique=False)
    op.create_table('social_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reporter_user_id', sa.BigInteger(), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=True),
    sa.Column('comment_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('reviewed_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['social_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_reports_comment_id'), 'social_reports', ['comment_id'], unique=False)
    op.create_index(op.f('ix_social_reports_post_id'), 'social_reports', ['post_id'], unique=False)
    op.create_index(op.f('ix_social_reports_reporter_user_id'), 'social_reports', ['reporter_user_id'], unique=False)
    op.create_index(op.f('ix_social_reports_reviewed_by_user_id'), 'social_reports', ['reviewed_by_user_id'], unique=False)
    op.create_index('ix_social_reports_status_created', 'social_reports', ['status', 'created_at'], unique=False)
    op.create_index('ix_social_reports_target_status', 'social_reports', ['target_type', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_social_reports_target_status', table_name='social_reports')
    op.drop_index('ix_social_reports_status_created', table_name='social_reports')
    op.drop_index(op.f('ix_social_reports_reviewed_by_user_id'), table_name='social_reports')
    op.drop_index(op.f('ix_social_reports_reporter_user_id'), table_name='social_reports')
    op.drop_index(op.f('ix_social_reports_post_id'), table_name='social_reports')
    op.drop_index(op.f('ix_social_reports_comment_id'), table_name='social_reports')
    op.drop_table('social_reports')
    op.drop_index(op.f('ix_social_reactions_user_id'), table_name='social_reactions')
    op.drop_index('ix_social_reactions_user_created', table_name='social_reactions')
    op.drop_index(op.f('ix_social_reactions_post_id'), table_name='social_reactions')
    op.drop_index(op.f('ix_social_reactions_comment_id'), table_name='social_reactions')
    op.drop_table('social_reactions')
    op.drop_index('ix_social_moderation_target_created', table_name='social_moderation_actions')
    op.drop_index('ix_social_moderation_moderator_created', table_name='social_moderation_actions')
    op.drop_index(op.f('ix_social_moderation_actions_post_id'), table_name='social_moderation_actions')
    op.drop_index(op.f('ix_social_moderation_actions_moderator_user_id'), table_name='social_moderation_actions')
    op.drop_index(op.f('ix_social_moderation_actions_comment_id'), table_name='social_moderation_actions')
    op.drop_table('social_moderation_actions')
    op.drop_index('ix_social_comments_post_status_created', table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_post_id'), table_name='social_comments')
    op.drop_index('ix_social_comments_parent_created', table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_parent_comment_id'), table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_author_user_id'), table_name='social_comments')
    op.drop_table('social_comments')
    op.drop_index(op.f('ix_social_bookmarks_user_id'), table_name='social_bookmarks')
    op.drop_index('ix_social_bookmarks_user_created', table_name='social_bookmarks')
    op.drop_index(op.f('ix_social_bookmarks_post_id'), table_name='social_bookmarks')
    op.drop_table('social_bookmarks')
    op.drop_index(op.f('ix_social_posts_village_id'), table_name='social_posts')
    op.drop_index('ix_social_posts_type_status_created', table_name='social_posts')
    op.drop_index('ix_social_posts_status_created', table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_province_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_media_file_id'), table_name='social_posts')
    op.drop_index('ix_social_posts_geo', table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_country_code'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_city_id'), table_name='social_posts')
    op.drop_index('ix_social_posts_category_status_created', table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_category_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_author_user_id'), table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_index('ix_social_categories_active_sort', table_name='social_categories')
    op.drop_table('social_categories')
    # ### end Alembic commands ###
