"""add store tables

Revision ID: ec5e6bb244c3
Revises: 7494f17b14e8
Create Date: 2026-05-17 10:48:04.553108

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ec5e6bb244c3'
down_revision: str | Sequence[str] | None = '7494f17b14e8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('store_type', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('province_id', sa.BigInteger(), nullable=True),
    sa.Column('county_id', sa.BigInteger(), nullable=True),
    sa.Column('district_id', sa.BigInteger(), nullable=True),
    sa.Column('city_id', sa.BigInteger(), nullable=True),
    sa.Column('village_id', sa.BigInteger(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('logo_file_id', sa.String(length=255), nullable=True),
    sa.Column('banner_file_id', sa.String(length=255), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['auth_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['city_id'], ['geo_cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['county_id'], ['geo_counties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['geo_districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['auth_users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['province_id'], ['geo_provinces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rejected_by'], ['auth_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['village_id'], ['geo_villages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_approved_by'), 'stores', ['approved_by'], unique=False)
    op.create_index(op.f('ix_stores_city_id'), 'stores', ['city_id'], unique=False)
    op.create_index(op.f('ix_stores_county_id'), 'stores', ['county_id'], unique=False)
    op.create_index(op.f('ix_stores_district_id'), 'stores', ['district_id'], unique=False)
    op.create_index('ix_stores_geo', 'stores', ['province_id', 'county_id', 'city_id', 'village_id'], unique=False)
    op.create_index(op.f('ix_stores_name'), 'stores', ['name'], unique=False)
    op.create_index('ix_stores_owner_status', 'stores', ['owner_user_id', 'status'], unique=False)
    op.create_index(op.f('ix_stores_owner_user_id'), 'stores', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_stores_province_id'), 'stores', ['province_id'], unique=False)
    op.create_index('ix_stores_public_lookup', 'stores', ['status', 'deleted_at', 'slug'], unique=False)
    op.create_index(op.f('ix_stores_rejected_by'), 'stores', ['rejected_by'], unique=False)
    op.create_index(op.f('ix_stores_slug'), 'stores', ['slug'], unique=True)
    op.create_index(op.f('ix_stores_status'), 'stores', ['status'], unique=False)
    op.create_index(op.f('ix_stores_store_type'), 'stores', ['store_type'], unique=False)
    op.create_index(op.f('ix_stores_village_id'), 'stores', ['village_id'], unique=False)
    op.create_table('store_members',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('invited_by', sa.BigInteger(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['auth_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'user_id', name='uq_store_members_store_user')
    )
    op.create_index(op.f('ix_store_members_invited_by'), 'store_members', ['invited_by'], unique=False)
    op.create_index(op.f('ix_store_members_role'), 'store_members', ['role'], unique=False)
    op.create_index(op.f('ix_store_members_status'), 'store_members', ['status'], unique=False)
    op.create_index(op.f('ix_store_members_store_id'), 'store_members', ['store_id'], unique=False)
    op.create_index(op.f('ix_store_members_user_id'), 'store_members', ['user_id'], unique=False)
    op.create_index('ix_store_members_user_status', 'store_members', ['user_id', 'status'], unique=False)
    op.create_table('store_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=True),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['auth_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_status_history_changed_by'), 'store_status_history', ['changed_by'], unique=False)
    op.create_index('ix_store_status_history_store_created', 'store_status_history', ['store_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_store_status_history_store_id'), 'store_status_history', ['store_id'], unique=False)
    op.create_index(op.f('ix_store_status_history_to_status'), 'store_status_history', ['to_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_status_history_to_status'), table_name='store_status_history')
    op.drop_index(op.f('ix_store_status_history_store_id'), table_name='store_status_history')
    op.drop_index('ix_store_status_history_store_created', table_name='store_status_history')
    op.drop_index(op.f('ix_store_status_history_changed_by'), table_name='store_status_history')
    op.drop_table('store_status_history')
    op.drop_index('ix_store_members_user_status', table_name='store_members')
    op.drop_index(op.f('ix_store_members_user_id'), table_name='store_members')
    op.drop_index(op.f('ix_store_members_store_id'), table_name='store_members')
    op.drop_index(op.f('ix_store_members_status'), table_name='store_members')
    op.drop_index(op.f('ix_store_members_role'), table_name='store_members')
    op.drop_index(op.f('ix_store_members_invited_by'), table_name='store_members')
    op.drop_table('store_members')
    op.drop_index(op.f('ix_stores_village_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_store_type'), table_name='stores')
    op.drop_index(op.f('ix_stores_status'), table_name='stores')
    op.drop_index(op.f('ix_stores_slug'), table_name='stores')
    op.drop_index(op.f('ix_stores_rejected_by'), table_name='stores')
    op.drop_index('ix_stores_public_lookup', table_name='stores')
    op.drop_index(op.f('ix_stores_province_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_owner_user_id'), table_name='stores')
    op.drop_index('ix_stores_owner_status', table_name='stores')
    op.drop_index(op.f('ix_stores_name'), table_name='stores')
    op.drop_index('ix_stores_geo', table_name='stores')
    op.drop_index(op.f('ix_stores_district_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_county_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_city_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_approved_by'), table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
