"""add profile verification tables

Revision ID: ed39d44aae11
Revises: e28c2056fa9d
Create Date: 2026-05-11 15:40:52.627832

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ed39d44aae11'
down_revision: str | Sequence[str] | None = 'e28c2056fa9d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=150), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['auth_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_documents_document_type'), 'user_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_user_documents_reviewed_by'), 'user_documents', ['reviewed_by'], unique=False)
    op.create_index(op.f('ix_user_documents_status'), 'user_documents', ['status'], unique=False)
    op.create_index(op.f('ix_user_documents_user_id'), 'user_documents', ['user_id'], unique=False)
    op.create_index('ix_user_documents_user_type_status', 'user_documents', ['user_id', 'document_type', 'status'], unique=False)
    op.create_table('verification_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('target_role', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('request_note', sa.Text(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['auth_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_requests_reviewed_by'), 'verification_requests', ['reviewed_by'], unique=False)
    op.create_index(op.f('ix_verification_requests_status'), 'verification_requests', ['status'], unique=False)
    op.create_index('ix_verification_requests_status_created', 'verification_requests', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_verification_requests_target_role'), 'verification_requests', ['target_role'], unique=False)
    op.create_index(op.f('ix_verification_requests_user_id'), 'verification_requests', ['user_id'], unique=False)
    op.create_index('ix_verification_requests_user_role_status', 'verification_requests', ['user_id', 'target_role', 'status'], unique=False)
    op.create_table('verification_request_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('verification_request_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['user_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verification_request_id'], ['verification_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_request_id', 'document_id', name='uq_verification_request_documents_request_document')
    )
    op.create_index(op.f('ix_verification_request_documents_document_id'), 'verification_request_documents', ['document_id'], unique=False)
    op.create_index(op.f('ix_verification_request_documents_verification_request_id'), 'verification_request_documents', ['verification_request_id'], unique=False)
    op.create_table('verification_reviews',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('verification_request_id', sa.BigInteger(), nullable=False),
    sa.Column('reviewer_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verification_request_id'], ['verification_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_reviews_action'), 'verification_reviews', ['action'], unique=False)
    op.create_index('ix_verification_reviews_request_action', 'verification_reviews', ['verification_request_id', 'action'], unique=False)
    op.create_index(op.f('ix_verification_reviews_reviewer_id'), 'verification_reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_verification_reviews_verification_request_id'), 'verification_reviews', ['verification_request_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('province_id', sa.BigInteger(), nullable=True),
    sa.Column('county_id', sa.BigInteger(), nullable=True),
    sa.Column('district_id', sa.BigInteger(), nullable=True),
    sa.Column('rural_district_id', sa.BigInteger(), nullable=True),
    sa.Column('city_id', sa.BigInteger(), nullable=True),
    sa.Column('village_id', sa.BigInteger(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('avatar_file_id', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['geo_cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['county_id'], ['geo_counties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['geo_districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['province_id'], ['geo_provinces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rural_district_id'], ['geo_rural_districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['village_id'], ['geo_villages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_city_id'), 'user_profiles', ['city_id'], unique=False)
    op.create_index(op.f('ix_user_profiles_county_id'), 'user_profiles', ['county_id'], unique=False)
    op.create_index(op.f('ix_user_profiles_district_id'), 'user_profiles', ['district_id'], unique=False)
    op.create_index('ix_user_profiles_geo', 'user_profiles', ['province_id', 'county_id', 'city_id', 'village_id'], unique=False)
    op.create_index('ix_user_profiles_name', 'user_profiles', ['first_name', 'last_name'], unique=False)
    op.create_index(op.f('ix_user_profiles_national_id'), 'user_profiles', ['national_id'], unique=True)
    op.create_index(op.f('ix_user_profiles_province_id'), 'user_profiles', ['province_id'], unique=False)
    op.create_index(op.f('ix_user_profiles_rural_district_id'), 'user_profiles', ['rural_district_id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_profiles_village_id'), 'user_profiles', ['village_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_village_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_rural_district_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_province_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_national_id'), table_name='user_profiles')
    op.drop_index('ix_user_profiles_name', table_name='user_profiles')
    op.drop_index('ix_user_profiles_geo', table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_district_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_county_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_city_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_verification_reviews_verification_request_id'), table_name='verification_reviews')
    op.drop_index(op.f('ix_verification_reviews_reviewer_id'), table_name='verification_reviews')
    op.drop_index('ix_verification_reviews_request_action', table_name='verification_reviews')
    op.drop_index(op.f('ix_verification_reviews_action'), table_name='verification_reviews')
    op.drop_table('verification_reviews')
    op.drop_index(op.f('ix_verification_request_documents_verification_request_id'), table_name='verification_request_documents')
    op.drop_index(op.f('ix_verification_request_documents_document_id'), table_name='verification_request_documents')
    op.drop_table('verification_request_documents')
    op.drop_index('ix_verification_requests_user_role_status', table_name='verification_requests')
    op.drop_index(op.f('ix_verification_requests_user_id'), table_name='verification_requests')
    op.drop_index(op.f('ix_verification_requests_target_role'), table_name='verification_requests')
    op.drop_index('ix_verification_requests_status_created', table_name='verification_requests')
    op.drop_index(op.f('ix_verification_requests_status'), table_name='verification_requests')
    op.drop_index(op.f('ix_verification_requests_reviewed_by'), table_name='verification_requests')
    op.drop_table('verification_requests')
    op.drop_index('ix_user_documents_user_type_status', table_name='user_documents')
    op.drop_index(op.f('ix_user_documents_user_id'), table_name='user_documents')
    op.drop_index(op.f('ix_user_documents_status'), table_name='user_documents')
    op.drop_index(op.f('ix_user_documents_reviewed_by'), table_name='user_documents')
    op.drop_index(op.f('ix_user_documents_document_type'), table_name='user_documents')
    op.drop_table('user_documents')
    # ### end Alembic commands ###
