"""add auth tables

Revision ID: f1fe081114b3
Revises: 
Create Date: 2026-05-07 18:13:31.479156

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f1fe081114b3'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module', sa.String(length=80), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_permissions_code'), 'auth_permissions', ['code'], unique=True)
    op.create_index(op.f('ix_auth_permissions_is_active'), 'auth_permissions', ['is_active'], unique=False)
    op.create_index(op.f('ix_auth_permissions_module'), 'auth_permissions', ['module'], unique=False)
    op.create_table('auth_roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_roles_code'), 'auth_roles', ['code'], unique=True)
    op.create_index(op.f('ix_auth_roles_is_active'), 'auth_roles', ['is_active'], unique=False)
    op.create_table('auth_users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_users_email'), 'auth_users', ['email'], unique=True)
    op.create_index(op.f('ix_auth_users_phone'), 'auth_users', ['phone'], unique=True)
    op.create_index(op.f('ix_auth_users_status'), 'auth_users', ['status'], unique=False)
    op.create_index('ix_auth_users_status_created_at', 'auth_users', ['status', 'created_at'], unique=False)
    op.create_table('auth_otp_codes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_otp_codes_phone'), 'auth_otp_codes', ['phone'], unique=False)
    op.create_index('ix_auth_otp_codes_phone_purpose_status', 'auth_otp_codes', ['phone', 'purpose', 'status'], unique=False)
    op.create_index(op.f('ix_auth_otp_codes_purpose'), 'auth_otp_codes', ['purpose'], unique=False)
    op.create_index(op.f('ix_auth_otp_codes_status'), 'auth_otp_codes', ['status'], unique=False)
    op.create_table('auth_role_permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_auth_role_permissions_role_permission')
    )
    op.create_index('ix_auth_role_permissions_permission_id', 'auth_role_permissions', ['permission_id'], unique=False)
    op.create_index('ix_auth_role_permissions_role_id', 'auth_role_permissions', ['role_id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_status'), 'auth_sessions', ['status'], unique=False)
    op.create_index('ix_auth_sessions_user_status', 'auth_sessions', ['user_id', 'status'], unique=False)
    op.create_table('auth_user_roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_by', sa.BigInteger(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['auth_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_auth_user_roles_user_role')
    )
    op.create_index('ix_auth_user_roles_role_id', 'auth_user_roles', ['role_id'], unique=False)
    op.create_index('ix_auth_user_roles_user_id', 'auth_user_roles', ['user_id'], unique=False)
    op.create_table('auth_refresh_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=True),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['auth_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_auth_refresh_tokens_status'), 'auth_refresh_tokens', ['status'], unique=False)
    op.create_index('ix_auth_refresh_tokens_user_status', 'auth_refresh_tokens', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_refresh_tokens_user_status', table_name='auth_refresh_tokens')
    op.drop_index(op.f('ix_auth_refresh_tokens_status'), table_name='auth_refresh_tokens')
    op.drop_table('auth_refresh_tokens')
    op.drop_index('ix_auth_user_roles_user_id', table_name='auth_user_roles')
    op.drop_index('ix_auth_user_roles_role_id', table_name='auth_user_roles')
    op.drop_table('auth_user_roles')
    op.drop_index('ix_auth_sessions_user_status', table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_status'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index('ix_auth_role_permissions_role_id', table_name='auth_role_permissions')
    op.drop_index('ix_auth_role_permissions_permission_id', table_name='auth_role_permissions')
    op.drop_table('auth_role_permissions')
    op.drop_index(op.f('ix_auth_otp_codes_status'), table_name='auth_otp_codes')
    op.drop_index(op.f('ix_auth_otp_codes_purpose'), table_name='auth_otp_codes')
    op.drop_index('ix_auth_otp_codes_phone_purpose_status', table_name='auth_otp_codes')
    op.drop_index(op.f('ix_auth_otp_codes_phone'), table_name='auth_otp_codes')
    op.drop_table('auth_otp_codes')
    op.drop_index('ix_auth_users_status_created_at', table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_status'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_phone'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.drop_table('auth_users')
    op.drop_index(op.f('ix_auth_roles_is_active'), table_name='auth_roles')
    op.drop_index(op.f('ix_auth_roles_code'), table_name='auth_roles')
    op.drop_table('auth_roles')
    op.drop_index(op.f('ix_auth_permissions_module'), table_name='auth_permissions')
    op.drop_index(op.f('ix_auth_permissions_is_active'), table_name='auth_permissions')
    op.drop_index(op.f('ix_auth_permissions_code'), table_name='auth_permissions')
    op.drop_table('auth_permissions')
    # ### end Alembic commands ###
